liip_imagine:
    filter_sets:
        admin_sidebar_logo:
            filters:
                relative_resize:
                    widen: 250
        admin_login_logo:
            filters:
                relative_resize:
                    widen: 250
        admin_login_background:
            filters:
                relative_resize:
                    widen: 1600
