sylius_ui:
    events:
        sylius.admin.layout.stylesheets:
            blocks:
                monsieurbiz_better_admin_stylesheet:
                    template: "@MonsieurBizSyliusBetterAdminPlugin/Admin/_styles.html.twig"
